const { fs, path, os, assert, runCli } = require('../test-utils');

module.exports = {
  name: '--init generates valid config from interactive input',
  run: () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ppcr-init-test-'));
    fs.mkdirSync(path.join(tempDir, 'collections'), { recursive: true });
    fs.mkdirSync(path.join(tempDir, 'environments'), { recursive: true });

    const answers = [
      './collections',
      '',
      '',
      'yes',
      './environments',
      '3',
      './results'
    ].join('\n') + '\n';

    try {
      const result = runCli(['--init'], { cwd: tempDir, input: answers });
      const output = `${result.stdout}\n${result.stderr}`;
      assert.strictEqual(result.status, 0, `Expected init to exit 0, got ${result.status}\n${output}`);

      const generatedConfigPath = path.join(tempDir, 'config.json');
      assert.ok(fs.existsSync(generatedConfigPath), 'Expected config.json to be generated by --init');

      const generatedConfig = JSON.parse(fs.readFileSync(generatedConfigPath, 'utf8'));
      assert.strictEqual(generatedConfig.collectionsFolder, './collections');
      assert.strictEqual(generatedConfig.parallel, true);
      assert.strictEqual(generatedConfig.reporters, 'cli,html,json');
      assert.strictEqual(generatedConfig.outputDir, './results');
      assert.strictEqual(generatedConfig.environmentsFolder, './environments');
      assert.ok(!Array.isArray(generatedConfig.reporters), 'Expected reporters to be a string, not an array');
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }
};
